name: Deploy Snowflake FinOps App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Snowflake CLI
      run: |
        pip install snowflake-cli-labs
        
    - name: Configure Snowflake Connection
      env:
        SNOWFLAKE_ACCOUNT: ${{ secrets.SNOW_ACCOUNT }}
        SNOWFLAKE_USER: ${{ secrets.SNOW_USER }}
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOW_PW }}
        SNOWFLAKE_ROLE: ${{ secrets.SNOW_ROLE }}
        SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOW_WAREHOUSE }}
        SNOWFLAKE_DATABASE: ${{ secrets.SNOW_DATABASE }}
        SNOWFLAKE_SCHEMA: ${{ secrets.SNOW_SCHEMA }}
      run: |
        snow connection add default \
          --account "$SNOWFLAKE_ACCOUNT" \
          --user "$SNOWFLAKE_USER" \
          --role "$SNOWFLAKE_ROLE" \
          --warehouse "$SNOWFLAKE_WAREHOUSE" \
          --database "$SNOWFLAKE_DATABASE" \
          --schema "$SNOWFLAKE_SCHEMA"
          
    - name: Deploy SQL Objects
      env:
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOW_PW }}
      run: |
        for sql_file in sql/*.sql; do
          echo "Executing $sql_file"
          snow sql -f "$sql_file"
        done
        
    - name: Deploy Streamlit App
      env:
        SNOWFLAKE_PASSWORD: ${{ secrets.SNOW_PW }}
      run: |
        snow streamlit deploy \
          --replace \
          --name finops-app \
          --file app/streamlit_app.py