name: Deploy Snowflake FinOps App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Snowflake CLI
      run: |
        pip install snowflake-cli-labs
        
    - name: Setup Snowflake Private Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SNOWFLAKE_PRIVATE_KEY }}" > ~/.ssh/snowflake_key.p8
        chmod 600 ~/.ssh/snowflake_key.p8
        
    - name: Deploy Project
      env:
        SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
        SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
        SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
        SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
        SNOWFLAKE_PRIVATE_KEY_PATH: ~/.ssh/snowflake_key.p8
        SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }}
        SNOWFLAKE_AUTHENTICATOR: snowflake
      run: |
        echo "Deploying SQL objects..."
        for sql_file in sql/*.sql; do
          if [ -f "$sql_file" ]; then
            echo "Executing $sql_file"
            snow sql -f "$sql_file" --database "$SNOWFLAKE_DATABASE" --schema "$SNOWFLAKE_SCHEMA"
          fi
        done
        
        echo "Deploying Streamlit app..."
        snow streamlit deploy \
          --replace \
          finops-app