name: Deploy Snowflake FinOps App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Snowflake CLI
      run: |
        pip install snowflake-cli-labs
        
    - name: Deploy SQL Objects
      env:
        SNOWFLAKE_CONNECTIONS_DEFAULT_ACCOUNT: ${{ secrets.SNOW_ACCOUNT }}
        SNOWFLAKE_CONNECTIONS_DEFAULT_USER: ${{ secrets.SNOW_USER }}
        SNOWFLAKE_CONNECTIONS_DEFAULT_PASSWORD: ${{ secrets.SNOW_PW }}
        SNOWFLAKE_CONNECTIONS_DEFAULT_ROLE: ${{ secrets.SNOW_ROLE }}
        SNOWFLAKE_CONNECTIONS_DEFAULT_WAREHOUSE: ${{ secrets.SNOW_WAREHOUSE }}
        SNOWFLAKE_CONNECTIONS_DEFAULT_DATABASE: ${{ secrets.SNOW_DATABASE }}
        SNOWFLAKE_CONNECTIONS_DEFAULT_SCHEMA: ${{ secrets.SNOW_SCHEMA }}
      run: |
        echo "Deploying SQL objects..."
        for sql_file in sql/*.sql; do
          if [ -f "$sql_file" ]; then
            echo "Executing $sql_file"
            snow sql -f "$sql_file" --connection default
          fi
        done
        
    - name: Deploy Streamlit App
      env:
        SNOWFLAKE_CONNECTIONS_DEFAULT_ACCOUNT: ${{ secrets.SNOW_ACCOUNT }}
        SNOWFLAKE_CONNECTIONS_DEFAULT_USER: ${{ secrets.SNOW_USER }}
        SNOWFLAKE_CONNECTIONS_DEFAULT_PASSWORD: ${{ secrets.SNOW_PW }}
        SNOWFLAKE_CONNECTIONS_DEFAULT_ROLE: ${{ secrets.SNOW_ROLE }}
        SNOWFLAKE_CONNECTIONS_DEFAULT_WAREHOUSE: ${{ secrets.SNOW_WAREHOUSE }}
        SNOWFLAKE_CONNECTIONS_DEFAULT_DATABASE: ${{ secrets.SNOW_DATABASE }}
        SNOWFLAKE_CONNECTIONS_DEFAULT_SCHEMA: ${{ secrets.SNOW_SCHEMA }}
      run: |
        echo "Deploying Streamlit app..."
        snow streamlit deploy \
          --replace \
          --name finops-app \
          --file app/streamlit_app.py \
          --connection default